import 'dart:io';
import 'package:path_provider/path_provider.dart';

class CoreFileWriter {
  // Save a Dart file generated by AI
  static Future<String> saveDartFile(String filename, String content) async {
    try {
      final directory = await getApplicationDocumentsDirectory(); // e.g., /data/user/0/com.app.nexora/files
      final path = "${directory.path}/$filename";
      final file = File(path);
      await file.writeAsString(content);
      return "✅ File saved: $filename";
    } catch (e) {
      return "❌ Failed to save file: $e";
    }
  }

  // OPTIONAL: Save logs or JSON
  static Future<String> saveLog(String filename, String content) async {
    try {
      final directory = await getApplicationDocumentsDirectory();
      final file = File("${directory.path}/logs/$filename");
      await file.create(recursive: true);
      await file.writeAsString(content);
      return "✅ Log saved: $filename";
    } catch (e) {
      return "❌ Failed to save log: $e";
    }
  }
}
